CREATE TABLE POST(
POST_ID BIGSERIAL PRIMARY KEY;
CATEGORY VARCHAR NOT NULL;
POST_HEADING VARCHAR(64) NOT NULL;
POST_DESC VARCHAR NOT NULL;
CREATED_DATE DATE ;
UPDATED_DATE DATE;
PUBLISH_DATE DATE;
PUBLISH_STATUS CHAR(1);
AUTHOR VARCHAR(64) NOT NULL;
);

CREATE TABLE COMMENTS(
COMMENT_ID BIGSERIAL PRIMARY KEY;
POST_ID LONG FOREIGN KEY NOT NULL;
COMMENT_DESC VARCHAR(264) NOT NULL;
COMMENT_DATE DATE ;
COMMENTER_NAME VARCHAR(64);
);