CREATE TABLE POST(
POST_ID BIGSERIAL PRIMARY KEY;
CATEGORY VARCHAR NOT NULL;
POST_HEADING VARCHAR(64) NOT NULL;
POST_DESC VARCHAR NOT NULL;
AUTHOR_ID LONG FOREIGN KEY NOT NULL;
CREATED_DATE DATE ;
UPDATED_DATE DATE;
PUBLISH_DATE DATE;
PUBLISH_STATUS CHAR(1);
AUTHOR VARCHAR(64) NOT NULL;
);

CREATE TABLE COMMENTS(
COMMENT_ID BIGSERIAL PRIMARY KEY;
POST_ID LONG FOREIGN KEY NOT NULL;
COMMENT_DESC VARCHAR(264) NOT NULL;
COMMENT_DATE DATE ;
COMMENTER_NAME VARCHAR(64);
);

CREATE TABLE AUTHOR(
AUTHOR_ID BIGSERIAL PRIMARY KEY,
AUTHOR_NAME VARCHAR(64),
AUTHOR_MOBILE_NO INT(10),
AUTHOR_EMAIL VARCHAR(64),
AUTHOR_PROFESSION VARCHAR(64)
ACTIVE_STATUS VARCHAR(10),
CREATED_DATE DATE,
);

